---
- fail:
    msg: PostgreSQL version earlier than 9.5 not supported
  when: postgresql_version is version('9.5', '<')
- fail:
    msg: invalid value for parameter postgresql_setup_stage
  when: postgresql_setup_stage not in ['install', 'initdb', 'basebackup', 'write_recovery_conf']
- import_tasks: install.yml
- import_tasks: setup.yml
  when: postgresql_setup_stage != 'install'
