---
- hosts: all
  become: yes
  vars:
    postgresql_data_directory: '{{ drbd_mount_directory }}/pgsql/data'
    postgresql_extra_config_parameters: |
      restart_after_crash = off
    postgresql_control_as_service: no
    postgresql_setup_stage: initdb
  roles:
    - common
    - hosts
    - locale
    - drbd
    - postgresql
    - pacemaker
    - pacemaker-drbd
