---
- hosts: all
  become: yes
  vars:
    postgresql_auth_method: "{{ (postgresql_version is version('10', '>=') and pgpool2_version is version('4.0', '>=')) | ternary('scram-sha-256', 'md5') }}"
    postgresql_extra_config_parameters: |
      {% if pgpool2_backend_clustering_mode == 'snapshot_isolation' %}
      default_transaction_isolation = 'repeatable read'
      {% endif %}
      restart_after_crash = off
    postgresql_control_as_service: no
    postgresql_setup_stage: "{{ (pgpool2_backend_clustering_mode == 'streaming_replication') | ternary('write_recovery_conf', 'basebackup') }}"
    postgresql_use_rewind: yes
  roles:
    - common
    - hosts
    - locale
    - postgresql
    - pgpool2
