---
- fail:
    msg: Other than CentOS/Rocky/AlmaLinux, or version earlier than 7 not supported
  when: ansible_distribution not in ['CentOS', 'Rocky', 'AlmaLinux'] or ansible_distribution_major_version is version('7', '<')
