---
- fail:
    msg: Other than RHEL clone version 7 or later not supported
  when: ansible_distribution not in ['CentOS', 'Rocky', 'AlmaLinux', 'OracleLinux'] or ansible_distribution_major_version is version('7', '<')
- blockinfile:
    path: /etc/resolv.conf
    block: |
      nameserver 8.8.8.8
      nameserver 8.8.4.4
- block:
    - replace:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: ^(mirrorlist=.*)
        replace: '#\1'
    - replace:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: ^#(baseurl=http://)mirror(\..*)
        replace: \1vault\2
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version is version ('7', '<=')
- yum:
    name: ca-certificates
    state: latest
- import_tasks: hosts.yml
- import_tasks: locale.yml
- import_tasks: disksize.yml
