---
local_disk: >-
  {%- if ansible_distribution == 'AlmaLinux' -%}
  /dev/sda2
  {%- elif ansible_distribution == 'OracleLinux' -%}
  /dev/mapper/vg_main-lv_root
  {%- else -%}
  /dev/sda1
  {%- endif -%}
